server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    return 302 /react-mastery-lab/home;
  }

  location /react-mastery-lab/ {
    try_files $uri $uri/ /react-mastery-lab/index.html;
  }

  location /react-mastery-lab/assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}
